# Example input.yaml for training SevenNet-Polar
# This small model can be trained on CPU, though it is recommended to use GPU for better performance.

model:
  chemical_species: 'auto'
  cutoff: 6.0
  channel: 16
  lmax: 2
  num_convolution_layer: 3

train:
  random_seed: 1
  num_workers: 4
  epoch: 40

  is_train_stress: True
  is_train_bec: True
  energy_loss_weight: 1.0
  force_loss_weight: 0.3
  bec_loss_weight: 1.0
  stress_loss_weight: 1.0e-5
  
  loss: 'mse'
  optimizer: 'adam'
  optim_param:
      lr: 0.005
  scheduler: 'exponentiallr'
  scheduler_param:
      gamma: 0.992

  per_epoch: 5
  error_record:
    - ['Energy', 'RMSE']
    - ['Force', 'RMSE']
    - ['Stress', 'RMSE']
    - ['BornEffectiveCharges', 'DiagRMSE']
    - ['BornEffectiveCharges', 'OffDiagRMSE']
    - ['TotalLoss', 'None']

data:
  batch_size: 1
  data_divide_ratio: 0.1                        # Split dataset into training and validation sets by this ratio
  shift: 'per_atom_energy_mean'
  scale: 1.0
  data_format: 'ase'
  data_format_args:
    format: 'extxyz'
    index: '::'
  load_trainset_path: ['data.xyz']

